import { jsx as _jsx } from "react/jsx-runtime";
import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import { App } from '@/app/App';
import { Providers } from '@/app/providers';
import { NotePopout } from '@/components/shell/NotePopout';
import { QuickCapture } from '@/components/shell/QuickCapture';
import { applyTheme } from '@/lib/theme';
applyTheme('system');
const _params = new URLSearchParams(window.location.search);
const _noteId = _params.get('note');
const _isQuickCapture = _params.has('quick-capture');
ReactDOM.createRoot(document.getElementById('root')).render(_jsx(React.StrictMode, { children: _noteId ? (_jsx(NotePopout, { noteId: _noteId })) : _isQuickCapture ? (_jsx(QuickCapture, {})) : (_jsx(Providers, { children: _jsx(App, {}) })) }));
