/** The toolbar's formatting buttons: what each one wraps the selection in, and how they group. */
import { ImageIcon, LinkIcon } from '@phosphor-icons/react'
import { formatShortcut } from '@/lib/shortcut-label'
import type { FormattingAction } from '@/tools/markdown-editor/markdown-model'

export const FORMATTING_ACTIONS: FormattingAction[] = [
  // Group 1 — inline text formatting
  {
    label: 'B',
    title: `Bold (${formatShortcut('mod+b')})`,
    prefix: '**',
    suffix: '**',
    placeholder: 'bold text',
    group: 1,
  },
  {
    label: 'I',
    title: `Italic (${formatShortcut('mod+i')})`,
    prefix: '_',
    suffix: '_',
    placeholder: 'italic text',
    group: 1,
  },
  {
    label: '~~',
    title: 'Strikethrough',
    prefix: '~~',
    suffix: '~~',
    placeholder: 'strikethrough',
    group: 1,
  },
  { label: '`', title: 'Inline Code', prefix: '`', suffix: '`', placeholder: 'code', group: 1 },
  // Group 2 — headings
  {
    label: 'H1',
    title: 'Heading 1',
    prefix: '# ',
    suffix: '',
    placeholder: 'Heading',
    line: true,
    group: 2,
  },
  {
    label: 'H2',
    title: 'Heading 2',
    prefix: '## ',
    suffix: '',
    placeholder: 'Heading',
    line: true,
    group: 2,
  },
  {
    label: 'H3',
    title: 'Heading 3',
    prefix: '### ',
    suffix: '',
    placeholder: 'Heading',
    line: true,
    group: 2,
  },
  // Group 3 — structure / lists
  {
    label: '•',
    title: 'Bullet List',
    prefix: '- ',
    suffix: '',
    placeholder: 'item',
    line: true,
    group: 3,
  },
  {
    label: '1.',
    title: 'Numbered List',
    prefix: '1. ',
    suffix: '',
    placeholder: 'item',
    line: true,
    group: 3,
  },
  {
    label: '☐',
    title: 'Task List',
    prefix: '- [ ] ',
    suffix: '',
    placeholder: 'task',
    line: true,
    group: 3,
  },
  {
    label: '>',
    title: 'Blockquote',
    prefix: '> ',
    suffix: '',
    placeholder: 'quote',
    line: true,
    group: 3,
  },
  {
    label: '—',
    title: 'Horizontal Rule',
    prefix: '\n---\n',
    suffix: '',
    placeholder: '',
    line: true,
    group: 3,
  },
  // Group 4 — media / insertions
  {
    label: 'Link',
    title: 'Link',
    prefix: '[',
    suffix: '](url)',
    placeholder: 'link text',
    modal: 'link',
    group: 4,
    icon: LinkIcon,
  },
  {
    label: 'Image',
    title: 'Image',
    prefix: '![',
    suffix: '](url)',
    placeholder: 'alt text',
    modal: 'image',
    group: 4,
    icon: ImageIcon,
  },
  // Group 5 — code / data blocks
  {
    label: '```',
    title: 'Code Block',
    prefix: '```\n',
    suffix: '\n```',
    placeholder: 'code',
    line: true,
    modal: 'code',
    group: 5,
  },
  {
    label: '⊞',
    title: 'Table',
    prefix: '| Column 1 | Column 2 | Column 3 |\n|----------|----------|----------|\n| ',
    suffix: ' |  |  |',
    placeholder: 'cell',
    line: true,
    modal: 'table',
    group: 5,
  },
]
